services:
  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=epgsql_test 
    restart: always
    ports:
      - 5432:5432
    volumes: []
